package enums;

public enum StatusEnum {
    BOOK_ADDED_SUCCESSFULLY,
    UPDATE_SUCCESSFULLY,
    DELETE_SUCCESSFULLY,
    SIGN_UP_SUCCESSFULLY,
    LOG_IN_SUCCESSFULLY,
    TICKET_TO_FILM_HAVE_BOUGHT_SUCCESSFULLY,
}
